apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: stock
spec:
  replicas: 1
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: stock-batch
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: stock-batch
    spec:
      # 定义容器，可以多个
      containers:
      - name: stock-batch
        image: url/stock-batch
