apiVersion: v1
kind: Service
metadata:
  name: stock-app-service
  namespace: stock
spec:
  selector:
    app: stock-app
  type: LoadBalancer
  ports:
    - port: 3001        # 本 Service 的端口
      targetPort: 3000  # 容器端口
